In [ ]:
import gzip 
from numpy.random import choice
import numpy as np 
import time
import tracemalloc

In [ ]:
def consume_cpu_ram(n): return np.ones((n, n))
def consume_cpu_ram_128mb(): return consume_cpu_ram(2**12)

In [ ]:
z = [consume_cpu_ram_128mb() for i in range(8)] # 1GB
del z
tracemalloc.start()
a1 = consume_cpu_ram_128mb()
a2 = consume_cpu_ram_128mb()
del a1

In [ ]:
a='''   1 gatttaagtg aatagcttgg ctatctcact tcccctcgtt ctcttgcaga actttgattt
       61 taacgaactt aaataaaagc cctgttgttt agcgtattgt tgcacttgtc tggtgggatt
      121 gtggcattaa tttgcctgct catctaggca gtggacatat gctcaacact gggtataatt
      181 ctaattgaat actatttttc agttagagcg tcgtgtctct tgtacgtctc ggtcacaata
      241 cacggtttcg tccggtgcgt ggcaattcgg ggcacatcat gtctttcgtg gctggtgtga
      301 ccgcgcaagg tgcgcgcggt acgtatcgag cagcgctcaa ctctgaaaaa catcaagacc
      361 atgtgtctct aactgtgcca ctctgtggtt caggaaacct ggttgaaaaa ctttcaccat
      421 ggttcatgga tggcgaaaat gcctatgaag tggtgaaggc catgttactt aaaaaggagc
      481 cacttctcta tgtgcccatc cggctggctg gacacactag acacctccca ggtcctcgtg
      541 tatacctggt tgagaggctc attgcttgtg aaaatccatt catggttaac caattggctt
      601 atagctctag tgcaaatggc agcttggttg gcacaatttt gcagggcaag cctattggta
      661 tgttcttccc ttatgacatc gaacttgtca caggaaagca aaatattctc ctgcgcaagt
      721 atggccgtgg tggttaccac tacaccccat tccactatga gcgagacaac acctcttgcc
      781 ctgagtggat ggacgatttt gaggcggatc ctaaaggcaa atatgcccag aatctgctta
      841 agaagttgat tggcggtgat gtcactccag ttgaccaata catgtgtggc gttgatggaa
      901 aacccattag tgcctacgca tttttaatgg ccaaggatgg aataaccaaa ctggctgatg
      961 ttgaagcgga cgtcgcagca cgtgctgatg acgaaggctt catcacatta aagaacaatc
     1021 tatatagatt ggtttggcat gttgagcgta aagacgttcc atatcctaag caatctattt
     1081 ttactattaa tagtgtggtc caaaaggatg gtgttgaaaa cactcctcct cactatttta
     1141 ctcttggatg caaaatttta acgctcaccc cacgcaacaa gtggagtggc gtttctgact
     1201 tgtccctcaa acaaaaactc ctttacacct tctatggtaa ggagtcactt gagaacccaa
     1261 cctacattta ccactccgca ttcattgagt gtggaagttg tggtaatgat tcctggctta
     1321 cagggaatgc tatccaaggg tttgcctgtg gatgtggggc atcatataca gctaatgatg
     1381 tcgaagtcca atcatctggc atgattaagc caaatgctct tctttgtgct acttgcccct
     1441 ttgctaaggg tgatagctgt tcttctaatt gcaaacattc agttgctcag ttggttagtt
     1501 acctttctga acgttgtaat gttattgctg attctaagtc cttcacactt atctttggtg
     1561 gcgtagctta cgcctacttt ggatgtgagg aaggtactat gtactttgtg cctagagcta
     1621 agtctgttgt ctcaaggatt ggagactcca tctttacagg ctgtactggc tcttggaaca
     1681 aggtcactca aattgctaac atgttcttgg aacagactca gcattccctt aactttgtgg
     1741 gagagttcgt tgtcaacgat gttgtcctcg caattctctc tggaaccaca actaatgttg
     1801 acaaaatacg ccagcttctc aaaggtgtca cccttgacaa gttgcgtgat tatttagctg
     1861 actatgacgt agcagtcact gccggcccat tcatggataa tgctattaat gttggtggta
     1921 caggattaca gtatgccgcc attactgcac cttatgtagt tctcactggc ttaggtgagt
     1981 cctttaagaa agttgcaacc ataccgtaca aggtttgcaa ctctgttaag gatactctga
     2041 cttattatgc tcacagcgtg ttgtacagag tttttcctta tgacatggat tctggtgtgt
     2101 catcctttag tgaactactt tttgattgcg ttgatctttc agtagcttct acctattttt
     2161 tagtccgcct cttgcaagat aagactggcg actttatgtc tacaattatt acttcctgcc
     2221 aaactgctgt tagtaagctt ctagatacat gttttgaagc tacagaagca acatttaact
     2281 tcttgttaga tttggcagga ttgttcagaa tctttcttcg caatgcctat gtgtacactt
     2341 cacaagggtt tgtggtggtc aatggcaaag tttctacact tgtcaaacaa gtgttagact
     2401 tgcttaataa gggtatgcaa cttttgcata caaaggtctc ctgggctggt tctaatatca
     2461 gtgctgttat ctacagcggc agggagtctt taatattccc atcgggaacc tattactgtg
     2521 tcaccactaa ggctaagtcc gttcaacaag atcttgacgt tattttgcct ggtgagtttt
     2581 ccaagaagca gttaggactg ctccaaccta ctgacaattc tacaactgtt agtgttactg
     2641 tatccagtaa catggttgaa actgttgtgg gtcaacttga gcaaactaat atgcatagtc
     2701 ctgatgttat agtaggtgac tatgtcatta ttagtgaaaa attgtttgtg cgtagtaagg
     2761 aagaagacgg atttgccttc taccctgctt gcactaatgg tcatgctgta ccgactctct
     2821 ttagacttaa gggaggtgca cctgtaaaaa aagtagcctt tggcggtgat caagtacatg
     2881 aggttgctgc tgtaagaagt gttactgtcg agtacaacat tcatgctgta ttagacacac
     2941 tacttgcttc ttctagtctt agaacctttg ttgtagataa gtctttgtca attgaggagt
     3001 ttgctgacgt agtaaaggaa caagtctcag acttgcttgt taaattactg cgtggaatgc
     3061 cgattccaga ttttgattta gacgatttta ttgacgcacc atgctattgc tttaacgctg
     3121 agggtgatgc atcttggtct tctactatga tcttctctct tcaccccgtc gagtgtgacg
     3181 aggagtgttc tgaagtagag gcttcagatt tagaagaagg tgaatcagag tgcatttctg
     3241 agacttcaac tgaacaagtt gacgtttctc atgagatttc tgacgacgag tgggctgctg
     3301 cagttgatga agcgttccct ctcgatgaag cagaagatgt tactgaatct gtgcaagaag
     3361 aagcacaacc agtagaagta cctgttgaag atattgcgca ggttgtcata gctgacacct
     3421 tacaggaaac tcctgttgtg tctgatactg ttgaagtccc accgcaagtg gtgaaacttc
     3481 cgtctgaacc tcagactatc cagcccgagg taaaagaagt tgcacctgtc tatgaggctg
     3541 ataccgaaca gacacagagt gttactgtta aacctaagag gttacgcaaa aagcgtaatg
     3601 ttgacccttt gtccaatttt gaacataagg ttattacaga gtgcgttacc atagttttag
     3661 gtgacgcaat tcaagtagcc aagtgctatg gtgagtctgt gttagttaat gctgctaaca
     3721 cacatcttaa gcatggcggt ggtatcgctg gtgctattaa tgcggcttca aaaggggctg
     3781 tccaaaaaga gtcagatgag tatattctgg ctaaagggcc gttacaagta ggagattcag
     3841 ttctcttgca aggccattct ctagctaaga atatcctgca tgtcgtaggc ccagatgccc
     3901 gcgctaaaca ggatgtttct ctccttagta agtgctataa ggctatgaat gcatatcctc
     3961 ttgtagtcac tcctcttgtt tcagcaggca tatttggtgt aaaaccagct gtgtcttttg
     4021 attatcttat tagagaggct aagactagag ttttagtcgt cgttaattcc caagatgtct
     4081 ataagagtct taccatagtt gacattccac agagtttgac tttttcatat gatgggttac
     4141 gtggcgcaat acgtaaagct aaagattatg gttttactgt ttttgtgtgc acagacaact
     4201 ctgctaacac taaagttctt aggaacaagg gtgttgatta tactaagaag tttcttacag
     4261 ttgacggtgt gcaatattat tgctacacgt ctaaggacac tttagatgat atcttacaac
     4321 aggctaataa gtctgttggt attatatcta tgcctttggg atatgtgtct catggtttag
     4381 acttaattca agcagggagt gtcgtgcgta gagttaacgt gccctacgtg tgtctcctag
     4441 ctaataaaga gcaagaagct attttgatgt ctgaagacgt taagttaaac ccttcagaag
     4501 attttataaa gcacgtccgc actaatggtg gttacaattc ttggcattta gtcgagggtg
     4561 aactattggt gcaagactta cgcttaaata agctcctgca ttggtctgat caaaccatat
     4621 gctacaagga tagtgtgttt tatgttgtaa agaatagtac agcttttcca tttgaaacac
     4681 tttcagcatg tcgtgcgtat ttggattcac gcacgacaca gcagttaaca atcgaagtct
     4741 tagtgactgt cgatggtgta aattttagaa cagtcgttct aaataataag aacacttata
     4801 gatcacagct tggatgcgtt ttctttaatg gtgctgatat ttctgatacc attcctgatg
     4861 agaaacagaa tggtcacagt ttatatctag cagacaattt gactgctgat gaaacaaagg
     4921 cgcttaaaga gttatatggc cccgttgatc ctactttctt acacagattc tattcactta
     4981 aggctgcagt ccataagtgg aagatggttg tgtgtgataa ggtacgttct ctcaaattga
     5041 gtgataataa ttgttatctt aatgcagtta ttatgacact tgatttattg aaggacatta
     5101 aatttgttat acctgctcta cagcatgcat ttatgaaaca taagggcggt gattcaactg
     5161 acttcatagc cctcattatg gcttatggca attgcacatt tggtgctcca gatgatgcct
     5221 ctcggttact tcataccgtg cttgcaaagg ctgagttatg ctgttctgca cgcatggttt
     5281 ggagagagtg gtgcaatgtc tgtggcataa aagatgttgt tctacaaggc ttaaaagctt
     5341 gttgttacgt gggtgtgcaa actgttgaag atctgcgtgc tcgcatgaca tatgtatgcc
     5401 agtgtggtgg tgaacgtcat cggcaaatag tcgaacacac caccccctgg ttgctgctct
     5461 caggcacacc aaatgaaaaa ttggtgacaa cctccacggc gcctgatttt gtagcgttta
     5521 atgtctttca gggcattgaa acggctgttg gccattatgt tcatgctcgc ctgaagggtg
     5581 gtcttatttt aaagtttgac tctggcaccg ttagcaagac ttcagactgg aagtgcaagg
     5641 tgacagatgt acttttctcc ggccaaaaat acagtagcga ttgtaatgtc gtacggtatt
     5701 ctttggacgg taatttcaga acagaggttg atcccgacct atctgctttc tatgttaagg
     5761 atggtaaata ctttacaagt gaaccacccg taacatattc accagctaca attttagctg
     5821 gtagtgtcta cactaatagc tgccttgtat cgtctgatgg acaacctggc ggtgatgcta
     5881 ttagtttgag ttttaataac cttttagggt ttgattctag taaaccagtc actaagaaat
     5941 acacttactc cttcttgcct aaagaagacg gcgatgtgtt gttggctgag tttgacactt
     6001 atgaccctat ttataagaat ggtgccatgt ataaaggcaa accaattctt tgggtcaaca
     6061 aagcatctta tgatactaat cttaataagt tcaatagagc tagtttgcgt caaatttttg
     6121 acgtagcccc cattgaactc gaaaataaat tcacaccttt gagtgtggag tctacaccag
     6181 ttgaacctcc aactgtagat gtggtagcac ttcaacagga aatgacaatt gtcaaatgta
     6241 agggtttaaa taaacctttc gtgaaggaca atgtcagttt cgttgctgat gactcaggta
     6301 ctcccgttgt tgagtatctg tctaaagaag atctacatac attgtatgta gaccctaagt
     6361 atcaagtcat tgtcttaaaa gacaatgtac tttcttctat gcttagattg cacaccgttg
     6421 agtcaggtga tattaacgtt gttgcagctt ccggatcttt gacacgtaaa gtgaaattac
     6481 tatttagggc ttcattttat ttcaaagaat ttgctacccg cactttcact gctaccactg
     6541 ctgtaggtag ttgtataaag agtgtagtgc ggcatctagg tgttactaaa ggcatattga
     6601 caggctgttt tagttttgtc aagatgttat ttatgcttcc actagcttac tttagtgatt
     6661 caaaactcgg caccacagag gttaaagtga gtgctttgaa aacagctggc gttgtgacag
     6721 gtaatgttgt aaaacagtgt tgcactgctg ctgttgattt aagtatggat aagttgcgcc
     6781 gtgtggattg gaaatcaacc ctacggttgt tacttatgtt atgcacaact atggtattgt
     6841 tgtcttctgt gtatcacttg tatgtcttca atcaggtctt atcaagtgat gttatgtttg
     6901 aagatgccca aggtttgaaa aagttctaca aagaagttag agcttaccta ggaatctctt
     6961 ctgcttgtga cggtcttgct tcagcttata gggcgaattc ctttgatgta cctacattct
     7021 gcgcaaaccg ttctgcaatg tgtaattggt gcttgattag ccaagattcc ataactcact
     7081 acccagctct taagatggtt caaacacatc ttagccacta tgttcttaac atagattggt
     7141 tgtggtttgc atttgagact ggtttggcat acatgctcta tacctcggcc ttcaactggt
     7201 tgttgttggc aggtacattg cattatttct ttgcacagac ttccatattt gtagactggc
     7261 ggtcatacaa ttatgctgtg tctagtgcct tctggttatt cacccacatt ccaatggcgg
     7321 gtttggtacg aatgtataat ttgttagcat gcctttggct tttacgcaag ttttatcagc
     7381 atgtaatcaa tggttgcaaa gatacggcat gcttgctctg ctataagagg aaccgactta
     7441 ctagagttga agcttctacc gttgtctgtg gtggaaaacg tacgttttat atcacagcaa
     7501 atggcggtat ttcattctgt cgtaggcata attggaattg tgtggattgt gacactgcag
     7561 gtgtggggaa taccttcatc tgtgaagaag tcgcaaatga cctcactacc gccctacgca
     7621 ggcctattaa cgctacggat agatcacatt attatgtgga ttccgttaca gttaaagaga
     7681 ctgttgttca gtttaattat cgtagagacg gtcaaccatt ctacgagcgg tttcccctct
     7741 gcgcttttac aaatctagat aagttgaagt tcaaagaggt ctgtaaaact actactggta
     7801 tacctgaata caactttatc atctacgact catcagatcg tggccaggaa agtttagcta
     7861 ggtctgcatg tgtttattat tctcaagtct tgtgtaaatc aattcttttg gttgactcaa
     7921 gtttggttac ttctgttggt gattctagtg aaatcgccac taaaatgttt gattcctttg
     7981 ttaatagttt cgtctcgctg tataatgtca cacgcgataa gttggaaaaa cttatctcta
     8041 ctgctcgtga tggcgtaagg cgaggcgata acttccatag tgtcttaaca acattcattg
     8101 acgcagcacg aggccccgca ggtgtggagt ctgatgttga gaccaatgaa attgttgact
     8161 ctgtgcagta tgctcataaa catgacatac aaattactaa tgagagttac aataattatg
     8221 taccctcata tgttaaacct gatagtgtgt ctaccagtga tttaggtagt ctcattgatt
     8281 gtaatgcggc ttcagttaac caaattgtct tgcgtaattc taatggtgct tgtatttgga
     8341 acgctgctgc atatatgaaa ctctcggatg cacttaaacg acagattcgc attgcatgcc
     8401 gtaagtgtaa tttagctttc cggttaacca cctcaaagct acgcgctaat gataatatct
     8461 tatcagttag attcactgct aacaaaattg ttggtggtgc tcctacatgg tttaatgcgt
     8521 tgcgtgactt tacgttaaag ggttacgttc ttgctaccat tattgtgttt ctgtgtgctg
     8581 tactgatgta tttgtgttta cctacatttt ctatggtacc tgttgaattt tatgaagacc
     8641 gcatcttgga ctttaaagtt cttgataatg gtatcattag ggatgtaaat cctgatgata
     8701 agtgctttgc taataagcac cggtccttca cacaatggta tcatgagcat gttggtggtg
     8761 tctatgacaa ctctatcaca tgcccattga cagttgcagt aattgctgga gttgctggtg
     8821 ctcgcattcc agacgtacct actacattgg cttgggtgaa caatcagata attttctttg
     8881 tttctcgagt ctttgctaat acaggcagtg tttgctacac tcctatagat gagataccct
     8941 ataagagttt ctctgatagt ggttgcattc ttccatctga gtgcactatg tttagggatg
     9001 cagagggccg tatgacacca tactgccatg atcctactgt tttgcctggg gcttttgcgt
     9061 acagtcagat gaggcctcat gttcgttacg acttgtatga tggtaacatg tttattaaat
     9121 ttcctgaagt agtatttgaa agtacactta ggattactag aactctgtca actcagtact
     9181 gccggttcgg tagttgtgag tatgcacaag agggtgtttg tattaccaca aatggctcgt
     9241 gggccatttt taatgaccac catcttaata gacctggtgt ctattgtggc tctgatttta
     9301 ttgacattgt caggcggtta gcagtatcac tgttccagcc tattacttat ttccaattga
     9361 ctacctcatt ggtcttgggt ataggtttgt gtgcgttcct gactttgctc ttctattata
     9421 ttaataaagt aaaacgtgct tttgcagatt acacccagtg tgctgtaatt gctgttgttg
     9481 ctgctgttct taatagcttg tgcatctgct ttgttgcctc tataccattg tgtatagtac
     9541 cttacactgc attgtactat tatgctacat tctattttac taatgagcct gcatttatta
     9601 tgcatgtttc ttggtacatt atgttcgggc ctatcgttcc catatggatg acctgcgttt
     9661 atacagttgc aatgtgcttt agacacttct tctgggtttt agcttatttt agtaagaaac
     9721 atgtagaagt ttttactgat ggtaagctta attgtagttt ccaggacgct gcctctaata
     9781 tctttgttat taacaaggac acttatgcag ctcttagaaa ctctttaact aatgatgcct
     9841 attcacgatt tttggggttg tttaacaagt ataagtactt ctctggtgct atggaaacag
     9901 ccgcttatcg tgaagctgca gcatgtcatc ttgctaaagc cttacaaaca tacagcgaga
     9961 ctggtagtga tcttctttac caaccaccca actgtagcat aacctctggc gtgttgcaaa
    10021 gcggtttggt gaaaatgtca catcccagtg gagatgttga ggcttgtatg gttcaggtta
    10081 cctgcggtag catgactctt aatggtcttt ggcttgacaa cacagtctgg tgcccacgac
    10141 acgtaatgtg cccggctgac cagttgtctg atcctaatta tgatgccttg ttgatttcta
    10201 tgactaatca tagtttcagt gtgcaaaaac acattggcgc tccagcaaac ttgcgtgttg
    10261 ttggtcatgc catgcaaggc actcttttga agttgactgt cgatgttgct aaccctagca
    10321 ctccagccta cacttttaca acagtgaaac ctggcgcagc atttagtgtg ttagcatgct
    10381 ataatggtcg tccgactggt acattcactg ttgtaatgcg ccctaactac acaattaagg
    10441 gttcctttct gtgtggttct tgtggtagtg ttggttacac caaggagggt agtgtgatca
    10501 atttttgtta catgcatcaa atggaacttg ctaatggtac acataccggt tcagcatttg
    10561 atggtactat gtatggtgcc tttatggata aacaagtgca ccaagttcag ttaacagaca
    10621 aatactgcag tgttaatgta gtagcttggc tttacgcagc aatacttaat ggttgcgctt
    10681 ggtttgtaaa acctaatcgc actagtgttg tttcttttaa tgaatgggct cttgccaacc
    10741 aattcactga atttgttggc actcaatccg ttgacatgtt agctgtcaaa acaggcgttg
    10801 ctattgaaca gctgctttat gcgatccaac aactttatac tgggttccag ggaaagcaaa
    10861 tccttggcag tactatgttg gaagatgaat tcacacctga ggatgttaat atgcagatta
    10921 tgggtgtggt tatgcagagt ggtgtgagaa aagttacata tggtactgcg cattggttgt
    10981 tcgcgaccct tgtctcaacc tatgtgataa tcttacaagc cactaaattt actttgtgga
    11041 actacttgtt tgagactatt cccacacagt tgttcccact cttatttgtg actatggcct
    11101 tcgttatgtt gttggttaaa cacaaacaca cctttttgac acttttcttg ttgcctgtgg
    11161 ctatttgttt gacttatgca aacatagtct acgagcccac tactcccatt tcgtcagcgc
    11221 tgattgcagt tgcaaattgg cttgccccca ctaatgctta tatgcgcact acacatactg
    11281 atattggtgt ctacattagt atgtcacttg tattagtcat tgtagtgaag agattgtaca
    11341 acccatcact ttctaacttt gcgttagcat tgtgcagtgg tgtaatgtgg ttgtacactt
    11401 atagcattgg agaagcctca agccccattg cctatctggt ttttgtcact acactcacta
    11461 gtgattatac gattacagtc tttgttactg tcaaccttgc aaaagtttgc acttatgcca
    11521 tctttgctta ctcaccacag cttacacttg tgtttccgga agtgaagatg atacttttat
    11581 tatacacatg tttaggtttc atgtgtactt gctattttgg tgtcttctct tttttgaacc
    11641 ttaagcttag agcacctatg ggtgtctatg actttaaggt ctcaacacaa gagttcagat
    11701 tcatgactgc taacaatcta actgcaccta gaaattcttg ggaggctatg gctctgaact
    11761 ttaagttaat aggtattggc ggtacacctt gtataaaggt tgctgctatg cagtctaaac
    11821 ttacagatct taaatgcaca tctgtggttc tcctctctgt gctccaacag ttacacttag
    11881 aggctaatag tagggcctgg gctttctgtg ttaaatgcca taatgatata ttggcagcaa
    11941 cagaccccag tgaggctttc gagaaattcg taagtctctt tgccacttta atgacttttt
    12001 ctggtaatgt agatcttgat gcgttagcta gtgatatttt tgacactcct agcgtacttc
    12061 aagctactct ttctgagttt tcacacttag ctacctttgc tgagttggaa gctgcgcaga
    12121 aagcctatca ggaagctatg gactctggtg acacctcacc acaagttctt aaggctttgc
    12181 agaaggctgt taatatagct aaaaacgcct atgagaagga taaggcagtg gcccgtaagt
    12241 tagaacgtat ggctgaccag gctatgactt ctatgtataa gcaagcacgt gctgaagaca
    12301 agaaagcaaa aattgtcagt gctatgcaaa ctatgttgtt tggtatgatt aagaagctcg
    12361 acaacgatgt tcttaatggt atcatttcta acgctaggaa tggttgtata cctcttagtg
    12421 tcattccact gtgtgcttca aataaacttc gcgttgtaat tcctgacttc accgtctgga
    12481 atcaggtagt cacatatccc tcgcttaact acgctggggc tttgtgggac attacagtta
    12541 taaacaatgt ggacaatgaa attgttaagt cttcagatgt tgtagacagc aatgaaaatt
    12601 taacatggcc acttgtttta gaatgcacta gggcatccac ttctgccgtt aagttgcaaa
    12661 ataatgagat caaaccttca ggtttaaaaa ccatggttgt gtctgcaggt caagagcaaa
    12721 ctaactgtaa tactagttcc ttagcttatt acgaacctgt gcagggtcgt aaaatgctga
    12781 tggctcttct ttctgataat gcctatctca aatgggcgcg tgttgaaggt aaggacggat
    12841 ttgttagtgt agagctacaa cctccttgca aattcttgat tgcgggacca aaaggacctg
    12901 aaatccgata tctctatttt gttaaaaatc ttaacaacct tcatcgcggg caagtgttag
    12961 ggcacattgc tgcgactgtt agattgcaag ctggttctaa caccgagttt gcctctaatt
    13021 cttcggtgtt gtcacttgtt aacttcaccg ttgatcctca aaaagcttat ctcgattttg
    13081 tcaatgcggg aggtgcccca ttgacaaatt gtgttaagat gcttactcct aaaactggta
    13141 caggtatagc tatatctgtt aaaccagaga gtacagctga tcaagagact tatggtggag
    13201 cttcagtgtg tctctattgc cgtgcgcata tagaacatcc tgatgtctct ggtgtttgta
    13261 aatataaggg taagtttgtc caaatccctg ctcagtgtgt ccgtgaccct gtgggatttt
    13321 gtttgtcaaa taccccctgt aatgtctgtc aatattggat tggatatggg tgcaattgtg
    13381 actcgcttag gcaagcagca ctgccccaat ctaaagattc caatttttta aacgagtccg
    13441 gggttctatt gtaaatgccc gaatagaacc ctgttcaagt ggtttgtcca ctgatgtcgt
    13501 ctttagggca tttgacatct gcaactataa ggctaaggtt gctggtattg gaaaatacta
    13561 caagactaat acttgtaggt ttgtagaatt agatgaccaa gggcatcatt tagactccta
    13621 ttttgtcgtt aagaggcata ctatggagaa ttatgaacta gagaagcact gttacgattt
    13681 gttacgtgac tgtgatgctg tagctcccca tgatttcttc atctttgatg tagacaaagt
    13741 taaaacacct catattgtac gtcagcgttt aactgagtac actatgatgg atcttgtata
    13801 tgccctgagg cactttgatc aaaatagcga agtgcttaag gctatcttag tgaagtatgg
    13861 ttgctgtgat gttacctact ttgaaaataa actctggttt gattttgttg aaaatcccag
    13921 tgttattggt gtttatcata aacttggaga acgtgtacgc caagctatct taaacactgt
    13981 taaattttgt gaccacatgg tcaaggctgg tttagtcggt gtgctcacac tagacaacca
    14041 ggaccttaat ggcaagtggt atgattttgg tgacttcgta atcactcaac ctggttcagg
    14101 agtagctata gttgatagct actattctta tttgatgcct gtgctctcaa tgaccgattg
    14161 tctggccgct gagacacata gggattgtga ttttaataaa ccactcattg agtggccact
    14221 tactgagtat gattttactg attataaggt acaactcttt gagaagtact ttaaatattg
    14281 ggatcagacg tatcacgcaa attgcgttaa ttgtactgat gaccgttgtg tgttacattg
    14341 tgctaatttc aatgtattgt ttgctatgac catgcctaag acttgtttcg gacccatagt
    14401 ccgaaagatc tttgttgatg gcgtgccatt tgtagtatct tgtggttatc actacaaaga
    14461 attaggttta gtcatgaata tggatgttag tctccataga cataggctct ctcttaagga
    14521 gttgatgatg tatgccgctg atccagccat gcacattgcc tcctctaacg cttttcttga
    14581 tttgaggaca tcatgtttta gtgtcgctgc acttacaact ggtttgactt ttcaaactgt
    14641 gcggcctggc aattttaacc aagacttcta tgatttcgtg gtatctaaag gtttctttaa
    14701 ggagggctct tcagtgacgc tcaaacattt tttctttgct caagatggta atgctgctat
    14761 tacagattat aattactatt cttataatct gcctactatg tgtgacatca aacaaatgtt
    14821 gttctgcatg gaagttgtaa acaagtactt cgaaatctat gacggtggtt gtcttaatgc
    14881 ttctgaagtg gttgttaata atttagacaa gagtgctggc catcctttta ataagtttgg
    14941 caaagctcgt gtctattatg agagcatgtc ttaccaggag caagatgaac tctttgccat
    15001 gacaaagcgt aacgtcattc ctaccatgac tcaaatgaat ctaaaatatg ctattagtgc
    15061 taagaataga gctcgcactg ttgcaggcgt gtccatactt agcacaatga ctaatcgcca
    15121 gtaccatcag aaaatgctta agtccatggc tgcaactcgt ggagcgactt gcgtcattgg
    15181 tactacaaag ttctatggtg gctgggattt catgcttaaa acattgtaca aagatgttga
    15241 taatccgcat cttatgggtt gggattaccc taagtgtgat agagctatgc ctaatatgtg
    15301 tagaatcttc gcttcactca tattagctcg taaacatggc acttgttgta ctacaaggga
    15361 cagattttat cgcttggcaa atgagtgtgc tcaggtgcta agcgaatatg ttctatgtgg
    15421 tggtggttac tacgtcaaac ctggaggtac cagtagcgga gatgccacca ctgcatatgc
    15481 caatagtgtc tttaacattt tgcaggcgac aactgctaat gtcagtgcac ttatgggtgc
    15541 taatggcaac aagattgttg acaaagaagt taaagacatg cagtttgatt tgtatgtcaa
    15601 tgtttacagg agcactagcc cagaccccaa atttgttgat aaatactatg cttttcttaa
    15661 taagcacttt tctatgatga tactgtctga tgacggtgtc gtttgctata atagtgatta
    15721 tgcagctaag ggttacattg ctggaataca gaattttaag gaaacgctgt attatcagaa
    15781 caatgtcttt atgtctgaag ctaaatgctg ggtggaaacc gatctgaaga aagggccaca
    15841 tgaattctgt tcacagcata cgctttatat taaggatggc gacgatggtt acttccttcc
    15901 ttatccagac ccttcaagaa ttttgtctgc cggttgcttt gtagatgata tcgttaagac
    15961 tgacggtaca ctcatggtag agcggtttgt gtctttggct atagatgctt accctctcac
    16021 aaagcatgaa gatatagaat accagaatgt attctgggtc tacttacagt atatagaaaa
    16081 actgtataaa gaccttacag gacacatgct tgacagttat tctgtcatgc tatgtggtga
    16141 taattctgct aagttttggg aagaggcatt ctacagagat ctctatagtt cgcctaccac
    16201 tttgcaggct gtcggttcat gcgttgtatg ccattcacag acttccctac gctgtgggac
    16261 atgcatccgt agaccatttc tctgctgtaa atgctgctat gatcatgtta tagcaactcc
    16321 acataagatg gttttgtctg tttctcctta cgtttgtaat gcccctggtt gtggcgtttc
    16381 agacgttact aagctatatt taggtggtat gagctacttt tgtgtagatc atagacctgt
    16441 gtgtagtttt ccactttgcg ctaatggtct tgtattcggc ttatacaaga atatgtgcac
    16501 aggtagtcct tctatagttg aatttaatag gttggctacc tgtgactgga ctgaaagtgg
    16561 tgattacacc cttgccaata ctacaacaga accactcaaa ctttttgctg ctgagacttt
    16621 acgtgccact gaagaggcgt ctaagcagtc ttatgctatt gccaccatca aagaaattgt
    16681 tggtgagcgc caactattac ttgtgtggga ggctggcaag tccaaaccac cactcaatcg
    16741 taattatgtt tttactggtt atcatataac caaaaatagt aaagtgcagc tcggtgagta
    16801 catcttcgag cgcattgatt atagtgatgc tgtatcctac aagtctagta caacgtataa
    16861 actgactgta ggtgacatct tcgtacttac ctctcactct gtggctacct tgacggcgcc
    16921 cacaattgtg aatcaagaga ggtatgttaa aattactggg ttgtacccaa ccattacggt
    16981 acctgaagag ttcgcaagtc atgttgccaa cttccaaaaa tcaggttata gtaaatatgt
    17041 cactgttcag ggaccacctg gcactggcaa aagtcatttt gctatagggt tagcgattta
    17101 ctaccctaca gcacgtgttg tttatacagc atgttcacac gcagctgttg atgctttgtg
    17161 tgaaaaagct tttaaatatt tgaacattgc taaatgttcc cgtatcattc ctgcaaaggc
    17221 acgtgttgag tgctatgaca ggtttaaagt taatgagaca aattctcaat atttgtttag
    17281 tactattaat gctctaccag aaacttctgc cgatattctg gtggttgatg aggttagtat
    17341 gtgcactaat tatgatcttt caattattaa tgcacgtatt aaagctaagc acattgtcta
    17401 tgtaggagat ccagcacagt tgccagctcc taggactttg ttgactagag gcacattgga
    17461 accagaaaat ttcaatagtg tcactagatt gatgtgtaac ttaggtcctg acatattttt
    17521 aagtatgtgc tacaggtgtc ctaaggaaat agtaagcact gtgagcgctc ttgtctacaa
    17581 taataaattg ttagccaaga aggagctttc aggccagtgc tttaaaatac tctataaggg
    17641 caatgtgacg catgatgcta gctctgccat taatagacca caactcacat ttgtgaagaa
    17701 ttttattact gccaatccgg catggagtaa ggcagtcttt atttcgcctt ataattcaca
    17761 gaatgctgtg gctcgttcaa tgctgggtct tactactcag actgttgatt cctcacaggg
    17821 ttcagaatac cagtatgtta tcttctgtca aacagcagat acggcacatg ctaacaacat
    17881 taacagattt aatgttgcaa tcactcgtgc ccaaaaaggt attctttgtg ttatgacatc
    17941 tcaggcactc tttgagtcct tagagtttac tgaattgtct tttactaatt acaagctcca
    18001 gtctcagatt gtaactggcc tttttaaaga ttgctctaga gaaacttctg gcctctcacc
    18061 tgcttatgca ccaacatacg ttagtgttga tgacaagtat aagacgagtg atgagctttg
    18121 cgtgaatctt aatttacccg caaatgtccc atactctcgt gttatttcca ggatgggctt
    18181 taaactcgat gcaacagttc ctggatatcc taagcttttc attactcgtg aagaggctgt
    18241 aaggcaagtt cgaagctgga taggcttcga tgttgagggt gctcatgctt cccgtaatgc
    18301 atgtggcacc aatgtgcctc tacaattagg attttcaact ggtgtgaact ttgttgttca
    18361 gccagttggt gttgtagaca ctgagtgggg taacatgtta acgggcattg ctgcccgtcc
    18421 tccaccaggt gaacagttta agcacctcgt gcctcttatg cataaggggg ctgcgtggcc
    18481 tattgttaga cgacgtatag tgcaaatgtt gtcagacact ttagacaaat tgtctgatta
    18541 ctgtacgttt gtttgttggg ctcatggctt tgaattaacg tctgcatcat acttttgcaa
    18601 gataggtaag gaacagaagt gttgcatgtg caatagacgc gctgcagcgt actcttcacc
    18661 tctgcaatct tatgcctgct ggactcattc ctgcggttat gattatgtct acaacccttt
    18721 ctttgtcgat gttcaacagt ggggttatgt aggcaatctt gctactaatc acgatcgtta
    18781 ttgctctgtc catcaaggag ctcatgtggc ttctaatgat gcaataatga ctcgttgttt
    18841 agctattcat tcttgtttta tagaacgtgt ggattgggat atagagtatc cttatatctc
    18901 acatgaaaag aaattgaatt cctgttgtag aatcgttgag cgcaacgtcg tacgtgctgc
    18961 tcttcttgcc ggttcatttg acaaagtcta tgatattggc aatcctaaag gaattcctat
    19021 tgttgatgac cctgtggttg attggcatta ttttgatgca cagcccttga ccagaaaggt
    19081 acaacagctt ttctatacag aggacatggc ctcaagattt gctgatgggc tctgcttatt
    19141 ttggaactgt aatgtaccaa aatatcctaa taatgcaatt gtatgcaggt ttgacacacg
    19201 tgtgcattct gagttcaatt tgccaggttg tgatggcggt agtttgtatg ttaacaagca
    19261 cgcttttcat acaccagcat atgatgtgag tgcattccgt gatctgaaac ctttaccatt
    19321 cttttattat tctactacac catgtgaagt gcatggtaat ggtagtatga tagaggatat
    19381 tgattatgta cccctaaaat ctgcagtctg tattacagct tgtaatttag ggggcgctgt
    19441 ttgtaggaag catgctacag agtacagaga gtatatggaa gcatataatc ttgtctctgc
    19501 atcaggtttc cgcctttggt gttataagac ctttgatatt tataatctct ggtctacttt
    19561 tacaaaagtt caaggtttgg aaaacattgc ttttaatgtt gttaaacaag gccattttat
    19621 tggtgttgag ggtgaactac ctgtagctgt agtcaatgat aagatcttca ccaagagtgg
    19681 cgttaatgac atttgtatgt ttgagaataa aaccactttg cctactaata tagcttttga
    19741 actctatgct aagcgtgctg tacgctcgca tcccgatttc aaattgctac acaatttaca
    19801 agcagacatt tgctacaagt tcgtcctttg ggattatgaa cgtagcaata tttatggtac
    19861 tgctactatt ggtgtatgta agtacactga tattgatgtt aattcagctt tgaatatatg
    19921 ttttgacata cgcgataatg gttcattgga gaagttcatg tctactccca atgccatctt
    19981 tatttctgat agaaaaatta agaaataccc ttgtatggta ggtcctgatt atgcttactt
    20041 caatggtgct atcatccgtg atagtgatgt tgttaaacaa ccagtgaagt tctacttgta
    20101 taagaaagtc aataatgagt ttattgatcc tactgagtgt atttacactc agagtcgctc
    20161 ttgtagtgac ttcctacccc tgtctgacat ggagaaagac tttctatctt ttgatagtga
    20221 tgttttcatt aagaagtatg gcttggaaaa ctatgctttt gagcacgtag tctatggaga
    20281 cttctctcat actacgttag gcggtcttca cttgcttatt ggtttataca agaagcaaca
    20341 ggaaggtcat attattatgg aagaaatgct aaaaggtagc tcaactattc ataactattt
    20401 tattactgag actaacacag cggcttttaa ggcggtgtgt tctgttatag atttaaagct
    20461 tgacgacttt gttatgattt taaagagtca agaccttggc gtagtatcca aggttgtcaa
    20521 ggttcctatt gacttaacaa tgattgagtt tatgttatgg tgtaaggatg gacaggttca
    20581 aaccttctac cctcgactcc aggcttctgc agattggaaa cctggtcatg caatgccatc
    20641 cctctttaaa gttcaaaatg taaaccttga acgttgtgag cttgctaatt acaagcaatc
    20701 tattcctatg cctcgcggtg tgcacatgaa catcgctaaa tatatgcaat tgtgccagta
    20761 tttaaatact tgcacattag ccgtgcctgc caatatgcgt gttatacatt ttggcgctgg
    20821 ttctgataaa ggtatcgctc ctggtacatc agttttacga cagtggcttc ctacagatgc
    20881 cattattata gataatgatt taaatgagtt cgtgtcagat gctgacataa ctttatttgg
    20941 agattgtgta actgtacgtg tcggccaaca agtggatctt gttatttccg acatgtatga
    21001 tcctactact aagaatgtaa caggtagtaa tgagtcaaag gctttattct ttacttacct
    21061 gtgtaacctc attaataata atcttgctct tggtgggtct gttgctatta aaataacaga
    21121 acactcttgg agcgttgaac tttatgaact tatgggaaaa tttgcttggt ggactgtttt
    21181 ctgcaccaat gcaaatgcat cctcatctga aggattcctc ttaggtatta attacttggg
    21241 tactattaaa gaaaatatag atggtggtgc tatgcacgcc aactatatat tttggagaaa
    21301 ttccactcct atgaatctga gtacttactc actttttgat ttatccaagt ttcaattaaa
    21361 attaaaagga acaccagttc ttcaattaaa ggagagtcaa attaacgaac tcgtaatatc
    21421 tctcctgtcg cagggtaagt tacttatccg tgacaatgat acactcagtg tttctactga
    21481 tgttcttgtt aacacctaca gaaagttacg ttgatgtagg gccagattct gttaagtctg
    21541 cttgtattga ggttgatata caacagactt tctttgataa aacttggcct aggccaattg
    21601 atgtttctaa ggctgacggt attatatacc ctcaaggccg tacatattct aacataacta
    21661 tcacttatca aggtcttttt ccctatcagg gagaccatgg tgatatgtat gtttactctg
    21721 caggacatgc tacaggcaca actccacaaa agttgtttgt agctaactat tctcaggacg
    21781 tcaaacagtt tgctaatggg tttgtcgtcc gtataggagc agctgccaat tccactggca
    21841 ctgttattat tagcccatct accagcgcta ctatacgaaa aatttaccct gcttttatgc
    21901 tgggttcttc agttggtaat ttctcagatg gtaaaatggg ccgcttcttc aatcatactc
    21961 tagttctttt gcccgatgga tgtggcactt tacttagagc tttttattgt attctagagc
    22021 ctcgctctgg aaatcattgt cctgctggca attcctatac ttcttttgcc acttatcaca
    22081 ctcctgcaac agattgttct gatggcaatt acaatcgtaa tgccagtctg aactctttta
    22141 aggagtattt taatttacgt aactgcacct ttatgtacac ttataacatt accgaagatg
    22201 agattttaga gtggtttggc attacacaaa ctgctcaagg tgttcacctc ttctcatctc
    22261 ggtatgttga tttgtacggc ggcaatatgt ttcaatttgc caccttgcct gtttatgata
    22321 ctattaagta ttattctatc attcctcaca gtattcgttc tatccaaagt gatagaaaag
    22381 cttgggctgc cttctacgta tataaacttc aaccgttaac tttcctgttg gatttttctg
    22441 ttgatggtta tatacgcaga gctatagact gtggttttaa tgatttgtca caactccact
    22501 gctcatatga atccttcgat gttgaatctg gagtttattc agtttcgtct ttcgaagcaa
    22561 aaccttctgg ctcagttgtg gaacaggctg aaggtgttga atgtgatttt tcacctcttc
    22621 tgtctggcac acctcctcag gtttataatt tcaagcgttt ggtttttacc aattgcaatt
    22681 ataatcttac caaattgctt tcactttttt ctgtgaatga ttttacttgt agtcaaatat
    22741 ctccagcagc aattgctagc aactgttatt cttcactgat tttggattat ttttcatacc
    22801 cacttagtat gaaatccgat ctcagtgtta gttctgctgg tccaatatcc cagtttaatt
    22861 ataaacagtc cttttctaat cccacatgtt tgattttagc gactgttcct cataacctta
    22921 ctactattac taagcctctt aagtacagct atattaacaa gtgctctcgt cttctttctg
    22981 atgatcgtac tgaagtacct cagttagtga acgctaatca atactcaccc tgtgtatcca
    23041 ttgtcccatc cactgtgtgg gaagacggtg attattatag gaaacaacta tctccacttg
    23101 aaggtggtgg ctggcttgtt gctagtggct caactgttgc catgactgag caattacaga
    23161 tgggctttgg tattacagtt caatatggta cagacaccaa tagtgtttgc cccaagcttg
    23221 aatttgctaa tgacacaaaa attgcctctc aattaggcaa ttgcgtggaa tattccctct
    23281 atggtgtttc gggccgtggt gtttttcaga attgcacagc tgtaggtgtt cgacagcagc
    23341 gctttgttta tgatgcgtac cagaatttag ttggctatta ttctgatgat ggcaactact
    23401 actgtttgcg tgcttgtgtt agtgttcctg tttctgtcat ctatgataaa gaaactaaaa
    23461 cccacgctac tctatttggt agtgttgcat gtgaacacat tttctctacc atgtctcaat
    23521 actcccgttc tacgcgatca atgcttaaac ggcgagattc tacatatggt ccccttcaga
    23581 cacctgttgg ttgtgtccta ggacttgtta attcctcttt gttcgtagag gactgcaagt
    23641 tgcctcttgg tcaatctctc tgtgctcttc ctgacacacc tagtactctc acacctcgca
    23701 gtgtgcgctc tgttccaggt gaaatgcgct tggcatccat tgcttttaat catcctattc
    23761 aggttgatca acttaatagt agttatttta aattaagtat acctactaat ttttcctttg
    23821 gtgtgactca ggagtacatt cagacaacca ttcagaaagt tactgttgat tgtaaacagt
    23881 acgtttgcaa tggtttccag aagtgtgagc aattactgcg cgagtatggc cagttttgtt
    23941 ccaaaataaa ccgggctctc catggtgcca atttacgcca ggatgattct gtacgtaatt
    24001 tgtttgcgag cgtgaaaagc tctcaatcat ctcctatcat accaggtttt ggaggtgact
    24061 ttaatttgac acttctagaa cctgtttcta tatctactgg cagtcgtagt gcacgtagtg
    24121 ctattgagga tttgctattt gacaaagtca ctatagctga tcctggttat atgcaaggtt
    24181 acgatgattg catgcagcaa ggtccagcat cagctcgtga tcttatttgt gctcaatatg
    24241 tggctggtta caaagtatta cctcctctta tggatgttaa tatggaagcc gcgtatacct
    24301 catctttgct tggcagcata gcaggtgttg gctggactgc tggcttatcc tcctttgctg
    24361 ctattccatt tgcacagagt atcttttata ggttaaacgg tgttggcatt actcaacagg
    24421 ttctttcaga gaaccaaaag cttattgcca ataagtttaa tcaggctctg ggagctatgc
    24481 aaacaggctt cactacaact aatgaagctt ttcggaaggt tcaggatgct gtgaacaaca
    24541 atgcacaggc tctatccaaa ttagctagcg agctatctaa tacttttggt gctatttccg
    24601 cctctattgg agacatcata caacgtcttg atgttctcga acaggacgcc caaatagaca
    24661 gacttattaa tggccgtttg acaacactaa atgcttttgt tgcacagcag cttgttcgtt
    24721 ccgaatcagc tgctctttcc gctcaattgg ctaaagataa agtcaatgag tgtgtcaagg
    24781 cacaatccaa gcgttctgga ttttgcggtc aaggcacaca tatagtgtcc tttgttgtaa
    24841 atgcccctaa tggcctttac ttcatgcatg ttggttatta ccctagcaac cacattgagg
    24901 ttgtttctgc ttatggtctt tgcgatgcag ctaaccctac taattgtata gcccctgtta
    24961 atggctactt tattaaaact aataacacta ggattgttga tgagtggtca tatactggct
    25021 cgtccttcta tgcacctgag cccatcacct ctcttaatac taagtatgtt gcaccacagg
    25081 tgacatacca aaacatttct actaacctcc ctcctcctct tctcggcaat tccaccggga
    25141 ttgacttcca agatgagttg gatgagtttt tcaaaaatgt tagcaccagt atacctaatt
    25201 ttggttctct aacacagatt aatactacat tactcgatct tacctacgag atgttgtctc
    25261 ttcaacaagt tgttaaagcc cttaatgagt cttacataga ccttaaagag cttggcaatt
    25321 atacttatta caacaaatgg ccgtggtaca tttggcttgg tttcattgct gggcttgttg
    25381 ccttagctct atgcgtcttc ttcatactgt gctgcactgg ttgtggcaca aactgtatgg
    25441 gaaaacttaa gtgtaatcgt tgttgtgata gatacgagga atacgacctc gagccgcata
    25501 aggttcatgt tcactaatta acgaactatc aatgagagtt caaagaccac ccactctctt
    25561 gttagtgttc tcactctctc ttttggtcac tgcattttca aaacctctct atgtacctga
    25621 gcattgtcag aattattctg gttgcatgct tagggcttgt attaaaactg cccaagctga
    25681 tacagctggt ctttatacaa attttcgaat tgacgtccca tctgcagaat caactggtac
    25741 tcaatcagtt tctgtcgatc gtgagtcaac ttcaactcat gatggtccta ccgaacatgt
    25801 tactagtgtg aatctttttg acgttggtta ctcagttaat taacgaactc tatggattac
    25861 gtgtctctgc ttaatcaaat ttggcagaag taccttaatt caccgtatac tacttgtttg
    25921 tatatcccta aacccacagc taagtataca cctttagttg gcacttcatt gcaccctgtg
    25981 ctgtggaact gtcagctatc ctttgctggt tatactgaat ctgctgttaa ttctacaaaa
    26041 gctttggcca aacaggacgc agctcagcga atcgcttggt tgctacataa ggatggagga
    26101 atccctgatg gatgttccct ctacctccgg cactcaagtt tattcgcgca aagcgaggaa
    26161 gaggagtcat tctccaacta agaaactgcg ctacgttaag cgtagatttt ctcttctgcg
    26221 ccctgaagac cttagtgtta ttgtccaacc aacacactat gtcagggtta cattttcaga
    26281 ccccaacatg tggtatctac gttcgggtca tcatttacac tcagttcaca attggcttaa
    26341 accttatggc ggccaacctg tttctgagta ccatattact ctagctttgc taaatctcac
    26401 tgatgaagat ttagctagag atttttcacc cattgcgctc tttttgcgca atgtcagatt
    26461 tgagctacat gagttcgcct tgctgcgcaa aactcttgtt cttaatgcat cagagatcta
    26521 ctgtgctaac atacatagat ttaagcctgt gtatagagtt aacacggcaa tccctactat
    26581 taaggattgg cttctcgttc agggattttc cctttaccat agtggcctcc ctttacatat
    26641 gtcaatctct aaattgcatg cactggatga tgttactcgc aattacatca ttacaatgcc
    26701 atgctttaga acttatcctc aacaaatgtt tgttactcct ttggccgtag atgttgtctc
    26761 catacggtct tccaatcagg gtaataaaca aattgttcat tcttacccca ttttacatca
    26821 tccaggattt taacgaacta tggctttctc ggcgtcttta tttaaacccg tccagctagt
    26881 cccagtttct cctgcatttc atcgcattga gtctactgac tctattgttt tcacatacat
    26941 tcctgctagc ggctatgtag ctgctttagc tgtcaatgtg tgtctcattc ccctattatt
    27001 actgctacgt caagatactt gtcgtcgcag cattatcaga actatggttc tctatttcct
    27061 tgttctgtat aactttttat tagccattgt actagtcaat ggtgtacatt atccaactgg
    27121 aagttgcctg atagccttct tagttatcct cataatactt tggtttgtag atagaattcg
    27181 tttctgtctc atgctgaatt cctacattcc actgtttgac atgcgttctc actttattcg
    27241 tgttagtaca gtttcttctc atggtatggt ccctgtcata cacaccaaac cattatttat
    27301 tagaaacttc gatcagcgtt gcagctgttc tcgttgtttt tatttgcact cttccactta
    27361 tatagagtgc acttatatta gccgttttag taagattagc ctagtttctg taactgactt
    27421 ctccttaaac ggcaatgttt ccactgtttt cgtgcctgca acgcgcgatt cagttcctct
    27481 tcacataatc gccccgagct cgcttatcgt ttaagcagct ctgcgctact atgggtcccg
    27541 tgtagaggct aatccattag tctctctttg gacatatgga aaacgaacta tgttaccctt
    27601 tgtccaagaa cgaatagggt tgttcatagt aaactttttc atttttaccg tagtatgtgc
    27661 tataacactc ttggtgtgta tggctttcct tacggctact agattatgtg tgcaatgtat
    27721 gacaggcttc aataccctgt tagttcagcc cgcattatac ttgtataata ctggacgttc
    27781 agtctatgta aaattccagg atagtaaacc ccctctacca cctgacgagt gggtttaacg
    27841 aactccttca taatgtctaa tatgacgcaa ctcactgagg cgcagattat tgccattatt
    27901 aaagactgga actttgcatg gtccctgatc tttctcttaa ttactatcgt actacagtat
    27961 ggatacccat cccgtagtat gactgtctat gtctttaaaa tgtttgtttt atggctccta
    28021 tggccatctt ccatggcgct atcaatattt agcgccattt atccaattga tctagcttcc
    28081 cagataatct ctggcattgt agcagctgtt tcagctatga tgtggatttc ctactttgtg
    28141 cagagtatcc ggctgtttat gagaactgga tcatggtggt cattcaatcc tgagactaat
    28201 tgccttttga acgttccatt tggtggtaca actgtcgtac gtccactcgt agaggactct
    28261 accagtgtaa ctgctgttgt aaccaatggc cacctcaaaa tggctggcat gcatttcggt
    28321 gcttgtgact acgacagact tcctaatgaa gtcaccgtgg ccaaacccaa tgtgctgatt
    28381 gctttaaaaa tggtgaagcg gcaaagctac ggaactaatt ccggcgttgc catttaccat
    28441 agatataagg caggtaatta caggagtccg cctattacgg cggatattga acttgcattg
    28501 cttcgagctt aggctcttta gtaagagtat cttaattgat tttaacgaat ctcaatttca
    28561 ttgttatggc atcccctgct gcacctcgtg ctgtttcctt tgccgataac aatgatataa
    28621 caaatacaaa cctgtctcga ggtagaggac gtaatccaaa accacgagct gcaccaaata
    28681 acactgtctc ttggtacact gggcttaccc aacacgggaa agtccctctt acctttccac
    28741 ctgggcaggg tgtacctctt aatgccaatt ccaccccagc gcaaaatgct gggtattggc
    28801 ggagacagga cagaaaaatt aataccggga atggaattaa gcaactggct cccaggtggt
    28861 acttctacta cactggaacc ggacccgaag cagcactccc attccgggct gttaaggatg
    28921 gcatcgtttg ggtccatgaa catggcgcca ctgatgctcc ttcaactttt gggacgcgga
    28981 accctaacaa tgattcagct attgttacac aattcgcgcc cggtactaag cttcctaaaa
    29041 acttccacat tgaggggact ggaggcaata gtcaatcatc ttcaagagcc tctagcgtaa
    29101 gcagaaactc ttccagatct agttcacaag gttcaagatc aggaaactct acccgcggca
    29161 cttctccagg tccatctgga atcggagcag taggaggtga tctactttac cttgatcttc
    29221 tgaacagact acaagccctt gagtctggca aagtaaagca atcgcagcca aaagtaatca
    29281 ctaagaaaga tgctgctgct gctaaaaata agatgcgcca caagcgcact tccaccaaaa
    29341 gtttcaacat ggtgcaagct tttggtcttc gcggaccagg agacctccag ggaaactttg
    29401 gtgatcttca attgaataaa ctcggcactg aggacccacg ttggccccaa attgctgagc
    29461 ttgctcctac agccagtgct tttatgggta tgtcgcaatt taaacttacc catcagaaca
    29521 atgatgatca tggcaaccct gtgtacttcc ttcggtacag tggagccatt aaacttgacc
    29581 caaagaatcc caactacaat aagtggttgg agcttcttga gcaaaatatt gatgcctaca
    29641 aaaccttccc taagaaggaa aagaaacaaa aggcaccaaa agaagaatca acagaccaaa
    29701 tgtctgaacc tcctaaggag cagcgtgtgc aaggtagcat cactcagcgc actcgcaccc
    29761 gtccaagtgt tcagcctggt ccaatgattg atgttaacac tgattagtgt cactcaaagt
    29821 aacaagatcg cggcaatcgt ttgtgtttgg taaccccatc tcaccatcgc ttgtccactc
    29881 ttgcacagaa tggaatcatg ttgtaattac agtgcaataa ggtaattata acccatttaa
    29941 ttgatagcta tgctttatta aagtgtgtag ctgtagagag aatgttaaag actgtcacct
    30001 ctgcctgatt gcaagtgaac agtgcccccc gggaagagct ctacagtgtg aaatgtaaat
    30061 aaaaatagct attattcaat tagattaggc taattagatg atttgcaaaa aaaaaaaaaa
    30121 aaa
'''    

In [ ]:
def clean(dna):
    num = '0123456789'
    for n in num:
        dna = dna.replace(n,'')
    dna = dna.replace('\n','') \
             .strip() \
             .replace(' ','')
    return dna

In [ ]:
covid_dna = clean(a)

In [ ]:
covid_dna 

'gatttaagtgaatagcttggctatctcacttcccctcgttctcttgcagaactttgattttaacgaacttaaataaaagccctgttgtttagcgtattgttgcacttgtctggtgggattgtggcattaatttgcctgctcatctaggcagtggacatatgctcaacactgggtataattctaattgaatactatttttcagttagagcgtcgtgtctcttgtacgtctcggtcacaatacacggtttcgtccggtgcgtggcaattcggggcacatcatgtctttcgtggctggtgtgaccgcgcaaggtgcgcgcggtacgtatcgagcagcgctcaactctgaaaaacatcaagaccatgtgtctctaactgtgccactctgtggttcaggaaacctggttgaaaaactttcaccatggttcatggatggcgaaaatgcctatgaagtggtgaaggccatgttacttaaaaaggagccacttctctatgtgcccatccggctggctggacacactagacacctcccaggtcctcgtgtatacctggttgagaggctcattgcttgtgaaaatccattcatggttaaccaattggcttatagctctagtgcaaatggcagcttggttggcacaattttgcagggcaagcctattggtatgttcttcccttatgacatcgaacttgtcacaggaaagcaaaatattctcctgcgcaagtatggccgtggtggttaccactacaccccattccactatgagcgagacaacacctcttgccctgagtggatggacgattttgaggcggatcctaaaggcaaatatgcccagaatctgcttaagaagttgattggcggtgatgtcactccagttgaccaatacatgtgtggcgttgatggaaaacccattagtgcctacgcatttttaatggccaaggatggaataaccaaactggctgatgttgaagcggacgtcgcagcacgtgctgatgacgaaggct

In [ ]:
base_tallies = []
base_tallies.append(covid_dna .count('a'))
base_tallies.append(covid_dna .count('g'))    
base_tallies.append(covid_dna .count('c')) 
base_tallies.append(covid_dna .count('t'))

In [ ]:
base_tallies

[7905, 6303, 6093, 9822]

In [ ]:
base_tallies = np.array(base_tallies).astype(float)

In [ ]:
base_tallies

array([7905., 6303., 6093., 9822.])

In [ ]:
sequence_length = float(len(covid_dna ))

In [ ]:
sequence_length

30123.0

In [ ]:
probabilities = base_tallies /sequence_length

In [ ]:
print(f'Sum of probs: {np.sum(probabilities)}')
print(f'Probs       : {probabilities}')
probabilities = probabilities/np.sum(probabilities)

Sum of probs: 1.0
Probs       : [0.26242406 0.20924211 0.20227069 0.32606314]


In [ ]:
print(f'Prob A: {probabilities[0]:0.3f}')
print(f'Prob G: {probabilities[1]:0.3f}')
print(f'Prob C: {probabilities[2]:0.3f}')
print(f'Prob T: {probabilities[3]:0.3f}')

Prob A: 0.262
Prob G: 0.209
Prob C: 0.202
Prob T: 0.326


In [ ]:
bases = ['a','g','c','t']


output_sequence_zero = []
for i in range(100): 
    output_sequence_zero.append(choice(bases,p=probabilities))

In [ ]:
log2_probability_zero = 0

In [ ]:
for base in covid_dna :
    base_index = bases.index(base)
    log2_probability_zero += np.log2(probabilities[base_index])

print(f'Log2Prob for Zeroth Order: {log2_probability_zero}')

Log2Prob for Zeroth Order: -59409.44863012953


In [ ]:
transition_probabilities = np.zeros(shape=(4,4))

In [ ]:
base_patterns = np.array([
['aa','at','ac','ag'],
['ta','tt','tc','tg'],
['ca','ct','cc','cg'],
['ga','gt','gc','gg']
])

In [ ]:
print('First Order Count')
for i in range(len(covid_dna) - 1):
    if (covid_dna[i] + covid_dna[i+1]) in base_patterns:
        x = np.where(base_patterns==(covid_dna[i]+covid_dna[i+1]))[0][0]
        y = np.where(base_patterns==(covid_dna[i]+covid_dna[i+1]))[1][0]
        transition_probabilities[x][y] += 1
print(transition_probabilities)
for row in transition_probabilities:
    row /= np.sum(row)

First Order Count
[[2199. 2286. 1763. 1656.]
 [2307. 3111. 1699. 2705.]
 [1925. 2304. 1152.  712.]
 [1474. 2121. 1479. 1229.]]


In [ ]:
print('Probability 1st')
print(transition_probabilities)
print(np.sum(transition_probabilities))
sequence = covid_dna.casefold()

print(f'Length of sequence:{len(sequence)}')

Probability 1st
[[0.27821356 0.28922065 0.22305162 0.20951417]
 [0.23488088 0.31673794 0.17297903 0.27540216]
 [0.31593632 0.37813885 0.18906942 0.11685541]
 [0.23385689 0.33650643 0.23465017 0.19498651]]
4.0
Length of sequence:30123


In [ ]:
first_base = choice(bases,p=probabilities)
output_sequence_first = [first_base]

for i in range(100):
    base_index = bases.index(output_sequence_first[-1])
    output_sequence_first.append( choice(bases,p=transition_probabilities[base_index]) )

In [ ]:
log2_probability_first = 0

for count,base in enumerate(covid_dna):
    if count == 0:
        log2_probability_first += np.log2(probabilities[bases.index(base)])
    else:
        index0 = bases.index(covid_dna[count-1])
        index1 = bases.index(covid_dna[count])
        log2_probability_first += np.log2(transition_probabilities[index0][index1])


print(f'Log2Prob for First Order: {log2_probability_first}')

Log2Prob for First Order: -62884.857831685


In [ ]:
transition_probabilities_2 = np.zeros(shape=(4,4,4))

base_patterns2 = np.array([
[['aaa','aag','aac','aat' ],['aga','agg','agc','agt' ],['aca','acg','acc','act' ],['ata','atg','atc','att' ]],
[['gaa','gag','gac','gat' ],['gga','ggg','ggc','ggt' ],['gca','gcg','gcc','gct' ],['gta','gtg','gtc','gtt' ]],
[['caa','cag','cac','cat' ],['cga','cgg','cgc','cgt' ],['cca','ccg','ccc','cct' ],['cta','ctg','ctc','ctt' ]],
[['taa','tag','tac','tat' ],['tga','tgg','tgc','tgt' ],['tca','tcg','tcc','tct' ],['tta','ttg','ttc','ttt' ]]
])

In [ ]:
print(" aaa = ",a.count('aaa'),"\t"," aga = ",a.count('aga'),"\t"," aca = ",a.count('aca'),"\t"," ata = ",a.count('ata'),"\n")
print(" aag = ",a.count('aag'),"\t"," agg = ",a.count('agg'),"\t"," acg = ",a.count('acg'),"\t"," atg = ",a.count('atg'),"\n")
print(" aac = ",a.count('aac'),"\t"," agc = ",a.count('agc'),"\t"," acc = ",a.count('acc'),"\t"," atc = ",a.count('atc'),"\n")
print(" aat = ",a.count('aat'),"\t"," agt = ",a.count('agt'),"\t"," act = ",a.count('act'),"\t"," att = ",a.count('att'),"\n")
print(" gaa = ",a.count('gaa'),"\t"," gga = ",a.count('gga'),"\t"," gca = ",a.count('gca'),"\t"," gta = ",a.count('gta'),"\n")
print(" gag = ",a.count('gag'),"\t"," ggg = ",a.count('ggg'),"\t"," gcg = ",a.count('gcg'),"\t"," gtg = ",a.count('gtg'),"\n")
print(" gac = ",a.count('gac'),"\t"," ggc = ",a.count('ggc'),"\t"," gcc = ",a.count('gcc'),"\t"," gtc = ",a.count('gtc'),"\n")
print(" gat = ",a.count('gat'),"\t"," ggt = ",a.count('ggt'),"\t"," gct = ",a.count('gct'),"\t"," gtt = ",a.count('gtt'),"\n")
print(" caa = ",a.count('caa'),"\t"," cga = ",a.count('cga'),"\t"," cca = ",a.count('cca'),"\t"," cta = ",a.count('cta'),"\n")
print(" cag = ",a.count('cag'),"\t"," cgg = ",a.count('cgg'),"\t"," ccg = ",a.count('ccg'),"\t"," ctg = ",a.count('ctg'),"\n")
print(" cac = ",a.count('cac'),"\t"," cgc = ",a.count('cgc'),"\t"," ccc = ",a.count('ccc'),"\t"," ctc = ",a.count('ctc'),"\n")
print(" cat = ",a.count('cat'),"\t"," cgt = ",a.count('cgt'),"\t"," cct = ",a.count('cct'),"\t"," ctt = ",a.count('ctt'),"\n")
print(" taa = ",a.count('taa'),"\t"," tga = ",a.count('tga'),"\t"," tca = ",a.count('tca'),"\t"," tta = ",a.count('tta'),"\n")
print(" tag = ",a.count('tag'),"\t"," tgg = ",a.count('tgg'),"\t"," tcg = ",a.count('tcg'),"\t"," ttg = ",a.count('ttg'),"\n")
print(" tac = ",a.count('tac'),"\t"," tgc = ",a.count('tgc'),"\t"," tcc = ",a.count('tcc'),"\t"," ttc = ",a.count('ttc'),"\n")
print(" tat = ",a.count('tat'),"\t"," tgt = ",a.count('tgt'),"\t"," tct = ",a.count('tct'),"\t"," ttt = ",a.count('ttt'),"\n")

 aaa =  360 	  aga =  363 	  aca =  458 	  ata =  371 

 aag =  424 	  agg =  271 	  acg =  176 	  atg =  563 

 aac =  344 	  agc =  280 	  acc =  277 	  atc =  280 

 aat =  497 	  agt =  410 	  act =  512 	  att =  604 

 gaa =  308 	  gga =  223 	  gca =  371 	  gta =  358 

 gag =  226 	  ggg =  118 	  gcg =  160 	  gtg =  406 

 gac =  263 	  ggc =  270 	  gcc =  192 	  gtc =  270 

 gat =  378 	  ggt =  370 	  gct =  459 	  gtt =  586 

 caa =  450 	  cga =  111 	  cca =  295 	  cta =  445 

 cag =  362 	  cgg =  103 	  ccg =  93 	  ctg =  479 

 cac =  337 	  cgc =  137 	  ccc =  147 	  ctc =  334 

 cat =  403 	  cgt =  220 	  cct =  335 	  ctt =  563 

 taa =  502 	  tga =  499 	  tca =  407 	  tta =  629 

 tag =  323 	  tgg =  472 	  tcg =  152 	  ttg =  674 

 tac =  444 	  tgc =  502 	  tcc =  262 	  ttc =  446 

 tat =  551 	  tgt =  664 	  tct =  503 	  ttt =  553 



In [ ]:
for i in range(len(sequence) - 2):
    if (sequence[i] + sequence[i+1] + sequence[i+2]) in base_patterns2:
        x = np.where(base_patterns2==(sequence[i]+sequence[i+1]+sequence[i+2]))[0][0]
        y = np.where(base_patterns2==(sequence[i]+sequence[i+1]+sequence[i+2]))[1][0]
        z = np.where(base_patterns2==(sequence[i]+sequence[i+1]+sequence[i+2]))[2][0]
        transition_probabilities_2[x][y][z] += 1

In [ ]:
for square in transition_probabilities_2:
    for row in square:
        row /= np.sum(row)
print('trans prob 2')
print(transition_probabilities_2)
print(np.sum(transition_probabilities_2))

trans prob 2
[[[0.27343039 0.23748863 0.20473157 0.28434941]
  [0.26871981 0.21437198 0.21014493 0.30676329]
  [0.3255814  0.11514464 0.19909246 0.36018151]
  [0.21084864 0.31233596 0.15004374 0.32677165]]

 [[0.26729986 0.20149254 0.21506106 0.31614654]
  [0.22620016 0.13018714 0.26932465 0.37428804]
  [0.31034483 0.13319811 0.16768087 0.3887762 ]
  [0.21923621 0.26874116 0.16171617 0.35030646]]

 [[0.29818182 0.22441558 0.22285714 0.25454545]
  [0.18679775 0.17977528 0.24719101 0.38623596]
  [0.33420139 0.10763889 0.19270833 0.36545139]
  [0.24609375 0.24869792 0.18706597 0.31814236]]

 [[0.27308192 0.17555267 0.24577373 0.30559168]
  [0.22809612 0.21663586 0.23068392 0.3245841 ]
  [0.29841083 0.11065333 0.19482048 0.39611536]
  [0.25490196 0.27258116 0.18707811 0.28543877]]]
16.0


In [ ]:
first_base  = choice(bases , p=probabilities)
second_base = choice(bases , p=transition_probabilities[bases.index(first_base)])
output_sequence_second = [first_base,second_base]

In [ ]:
for i in range(100):
    base_index_1 = bases.index(output_sequence_second[-1])
    base_index_0 = bases.index(output_sequence_second[-2])
    output_sequence_second.append( choice(bases,p=transition_probabilities_2[base_index_0][base_index_1]) )

In [ ]:
log2_probability_second = 0


for count,base in enumerate(sequence):
    if   count == 0:
        log2_probability_second += np.log2(probabilities[bases.index(base)])
    elif count == 1:
        base_index_0 = bases.index(sequence[count-1])
        base_index_1 = bases.index(sequence[count])
        log2_probability_second += np.log2(transition_probabilities[base_index_0][base_index_1])
    else:
        base_index_0 = bases.index(sequence[count-2])
        base_index_1 = bases.index(sequence[count-1])
        base_index_2 = bases.index(sequence[count])
        log2_probability_second += np.log2(transition_probabilities_2[base_index_0][base_index_1][base_index_2])

print(f'Log2Prob for Second Order: {log2_probability_second}')

Log2Prob for Second Order: -58682.12560247032


In [ ]:
states = ['A','G','C','T']

state_transition_probabilities = np.array([
    [0.4,0.4,0.1,0.1],
    [0.1,0.4,0.4,0.1],
    [0.1,0.1,0.4,0.4],
    [0.4,0.1,0.1,0.4]
])

state_emission_probabilities = np.array([
    [0.4,0.2,0.2,0.2],
    [0.2,0.4,0.2,0.2],
    [0.2,0.2,0.4,0.2],
    [0.2,0.2,0.2,0.4]
])

starting_state = choice(states)
state_sequence_hidden  = [starting_state]
output_sequence_hidden = [choice(bases,p=state_emission_probabilities[states.index(starting_state)]) ]

In [ ]:
for i in range(len(sequence)-1):
    state_index = states.index(state_sequence_hidden[-1])
    new_state   = choice(states,p=state_transition_probabilities[state_index])
    state_sequence_hidden.append(new_state)
    new_output  = choice(bases,p=state_emission_probabilities[states.index(new_state)])
    output_sequence_hidden.append(new_output)

In [ ]:
log_2_emission_probabilities   = np.log2(state_emission_probabilities)
log_2_transition_probabilities = np.log2(state_transition_probabilities) 
current_f  = np.array([0,0,0,0])
previous_f = np.array([0,-10000000,-10000000,-10000000])

In [ ]:
for base_count,base in enumerate(sequence):
    for current_state_count in range(4):
        emission_probability = log_2_emission_probabilities[current_state_count][bases.index(base)]
        b_array = np.array([0,0,0,0])
        for previous_state_count in range(4):
            b_array[previous_state_count] = previous_f[previous_state_count] + log_2_transition_probabilities[previous_state_count][current_state_count]
        b = np.max(b_array)
        term = 0
        for previous_state_count in range(4):
            term += 2**(previous_f[previous_state_count] + log_2_transition_probabilities[previous_state_count][current_state_count] - b) 
        current_f[current_state_count] = emission_probability + b + np.log2(term)

    if base_count != len(sequence)-1:
        previous_f = current_f

sequence_probability = np.sum(current_f)

print(f'Sequence Log2 Probability is: {sequence_probability}')

Sequence Log2 Probability is: -256693


In [ ]:
pip install hmmlearn

     |████████████████████████████████| 368kB 12.7MB/s 


In [ ]:
from hmmlearn import hmm
model = hmm.MultinomialHMM(n_components=len(states))
model.startprob_ = np.array([0.3, 0.4, 0.2, 0.1]) #self-defined

model.transmat_ = state_transition_probabilities
model.emissionprob_ = state_emission_probabilities

# Predict the optimal sequence of internal hidden state
X = np.atleast_2d([3,4,5,6,7]).T
model.fit(X)
state_sequence = model.predict(X)
prob_next_step = model.transmat_[state_sequence[-1], :]

print(prob_next_step)
print(model.decode(X))


#print(f'Running time: {end} seconds')

current, peak = list(map(lambda x: int(x/2**20), tracemalloc.get_traced_memory()))
tracemalloc.stop()
print(f"Memory used {current:0.2f}MB, {peak:0.2f}MB")

Even though the 'startprob_' attribute is set, it will be overwritten during initialization because 'init_params' contains 's'
Even though the 'transmat_' attribute is set, it will be overwritten during initialization because 'init_params' contains 't'
Fitting a model with 43 free scalar parameters with only 5 data points will result in a degenerate solution.


[1.38927511e-35 1.70227057e-33 6.20529157e-26 1.00000000e+00]
(-2.2139763288123318, array([0, 2, 3, 1, 2]))
Memory used 156.00MB, 256.00MB


In [ ]:
states = ['A','G','C','T','O']

state_transition_probabilities = np.array([
    [0.5   , 0.125 , 0.125 , 0.125 , 0.125],
    [0.125 , 0.5   , 0.125 , 0.125 , 0.125],
    [0.125 , 0.125 , 0.5   , 0.125 , 0.125],
    [0.125 , 0.125 , 0.125 , 0.5   , 0.125],
    [0.05  , 0.05  , 0.05  , 0.05  , 0.8]
])

state_emission_probabilities = np.array([
    [0.5   , 0.166 , 0.167 , 0.167],
    [0.166 , 0.5   , 0.167 , 0.167],
    [0.167 , 0.166 , 0.5   , 0.167],
    [0.167 , 0.167 , 0.166 , 0.5  ],
    [probabilities[0],probabilities[1],probabilities[2],probabilities[3]]
])

In [ ]:
from hmmlearn import hmm
model = hmm.MultinomialHMM(n_components=len(states))
model.startprob_ = np.array([0.3, 0.4, 0.2, 0.1]) #self-defined

model.transmat_ = state_transition_probabilities
model.emissionprob_ = state_emission_probabilities

# Predict the optimal sequence of internal hidden state
X = np.atleast_2d([3,4,5,6,7]).T
model.fit(X)
state_sequence = model.predict(X)
prob_next_step = model.transmat_[state_sequence[-1], :]

print(prob_next_step)
print(model.decode(X))

Even though the 'startprob_' attribute is set, it will be overwritten during initialization because 'init_params' contains 's'
Even though the 'transmat_' attribute is set, it will be overwritten during initialization because 'init_params' contains 't'
Fitting a model with 59 free scalar parameters with only 5 data points will result in a degenerate solution.


[1.00000000e+000 2.78795770e-200 6.83952779e-146 4.74264572e-165
 8.40195471e-051]
(-7.323024089429148e-09, array([2, 4, 1, 0, 3]))


In [ ]:
from hmmlearn import hmm
model = hmm.GaussianHMM(n_components=len(states))
model.startprob_ = np.array([0.3, 0.4, 0.2, 0.1]) #self-defined

model.transmat_ = state_transition_probabilities
model.emissionprob_ = state_emission_probabilities

# Predict the optimal sequence of internal hidden state
X = np.atleast_2d([3,4,5,6,7]).T
model.fit(X)
state_sequence = model.predict(X)
prob_next_step = model.transmat_[state_sequence[-1], :]

print(prob_next_step)
print(model.decode(X))

Even though the 'startprob_' attribute is set, it will be overwritten during initialization because 'init_params' contains 's'
Even though the 'transmat_' attribute is set, it will be overwritten during initialization because 'init_params' contains 't'
Fitting a model with 34 free scalar parameters with only 5 data points will result in a degenerate solution.


[0.00000000e+000 1.56947493e-052 1.16246445e-195 1.00000000e+000
 0.00000000e+000]
(6.918232798946864, array([4, 0, 2, 1, 3]))


In [ ]:

ai=0
ti=0
ci=0
gi=0
for count in range(len(sequence)):
    if sequence[count] == "a":
        ai+=1
    elif sequence[count] == "t":
        ti+=1
    elif sequence[count] == "c":
        ci+=1
    else:
        gi+=1

print(ai,ti,ci,gi)

7905 9822 6093 6303


In [ ]:
s = ['a', 't','c','g']
order1 = {}
for i in s:
    for j in s:
        order1[i+j]=0
for i in range(len(sequence)-1):
    i1 = sequence[i]
    i2 = sequence[i+1]
    order1[i1+i2]+=1

In [ ]:

order1

{'aa': 2199,
 'ac': 1763,
 'ag': 1656,
 'at': 2286,
 'ca': 1925,
 'cc': 1152,
 'cg': 712,
 'ct': 2304,
 'ga': 1474,
 'gc': 1479,
 'gg': 1229,
 'gt': 2121,
 'ta': 2307,
 'tc': 1699,
 'tg': 2705,
 'tt': 3111}

In [ ]:
order2 = {}
for i in s:
    for j in s:
        for k in s:
            order2[i+j+k]=0
for i in range(len(sequence) - 2):
    i1 = sequence[i]
    i2 = sequence[i+1]
    i3 = sequence[i+2]
    order2[i1+i2+i3]+=1

In [ ]:
order2

{'aaa': 601,
 'aac': 450,
 'aag': 522,
 'aat': 625,
 'aca': 574,
 'acc': 351,
 'acg': 203,
 'act': 635,
 'aga': 445,
 'agc': 348,
 'agg': 355,
 'agt': 508,
 'ata': 482,
 'atc': 343,
 'atg': 714,
 'att': 747,
 'caa': 574,
 'cac': 429,
 'cag': 432,
 'cat': 490,
 'cca': 385,
 'ccc': 222,
 'ccg': 124,
 'cct': 421,
 'cga': 133,
 'cgc': 176,
 'cgg': 128,
 'cgt': 275,
 'cta': 567,
 'ctc': 431,
 'ctg': 573,
 'ctt': 733,
 'gaa': 394,
 'gac': 317,
 'gag': 297,
 'gat': 466,
 'gca': 459,
 'gcc': 248,
 'gcg': 197,
 'gct': 575,
 'gga': 278,
 'ggc': 331,
 'ggg': 160,
 'ggt': 460,
 'gta': 465,
 'gtc': 343,
 'gtg': 570,
 'gtt': 743,
 'taa': 630,
 'tac': 567,
 'tag': 405,
 'tat': 705,
 'tca': 507,
 'tcc': 331,
 'tcg': 188,
 'tct': 673,
 'tga': 617,
 'tgc': 624,
 'tgg': 586,
 'tgt': 878,
 'tta': 793,
 'ttc': 582,
 'ttg': 848,
 'ttt': 888}